### ISSUE TITLE
inappbrowser spelling

### ISSUE THREAD

**Issue by mansxu** [teusink/jpHolo#3]
The file name "inappbrowser.js" is spelled all lowercase in **assets/www/cordova_plugins.js** but the actual file in **plugins/org.apache.cordova.inappbrowser/www/** is in camel-case: **InAppBrowser.js**

That aside, pretty **awesome** demo!!!

**Comment by kralito** [comment]
how can I make the div role="main" with 100% height?

thanks.

**Comment by teusink** [comment]
Thanks!
