### ISSUE TITLE
Role main 100% height

### ISSUE THREAD

**Issue by kralito** [teusink/jpHolo#5]
how can I make the div role="main" with 100% height?

thanks.

**Comment by teusink** [comment]
Check out main.html in the assets folder and look for this page:
<div id="immersivePage" data-role="page" data-theme="b">

That is an immersive page you are looking for (I think).

**Comment by kralito** [comment]
That's not what I need. I need to make a full height calendar with head . Like android calendar .

Thanks.

**Comment by teusink** [comment]
You mean content aligning directly on to the header in stead if whitespace between them?

**Comment by kralito** [comment]
Its OK now. Thanks.
