### ISSUE TITLE
Scrolling stop.

### ISSUE THREAD

**Issue by kralito** [teusink/jpHolo#6]
when I'm scrolling the content, it stops . I continue moving my finger but it does not scroll.

Sorry for my english

**Comment by kralito** [comment]
Here you have an example.

https://www.youtube.com/watch?v=EvHF4J0H6jQ

Maybe one plugin cause this?

**Comment by teusink** [comment]
It says, video is private :).
Are you running KitKat or newer? Or Jelly Bean or older?

**Comment by kralito** [comment]
Jelly Bean on S2 and KitKat con S5.
On S5 Scroll work well but when you stop and then you try to scrolling again does not work.
Here a video. https://www.youtube.com/watch?v=0xxOd9FWuFU

Now is public sorry.

**Comment by teusink** [comment]
I am afraid that it might be a complicated issue. There are some factors here that need to be considered.

- jQuery Mobile
- FastClick (to remove 300ms delay in none ChromeView webvies)
- Your own made elements
- Click and touch listeners

I cannot provide a clear solution to this, as I wrestled with it all the time also. When I was using jQuery Mobile + FastClick it all worked fine. It became tricky when adding own elements and especially own eventlisteners. When you create own toch effects it is important to factor in how events are handeld (when it is executed and when is it stopped).

You can also check if your issue exsists when FastClick is disabled. But FastClick should not activate on ChromeView enabled devices.

It seems that the first swipe it is seen as a touchmove, while the second swipe is seen as a tap (or touchdown/up), rather then a touchmove. This might be caused that after the first tap/touchmove the system is listening to the final touch. What you can do is add log events to every eventlistener (onClick and stuff) you have created yourself and check out which one is being executed and when it is executed. And work your way from there.

Keep in mind that this might be a timeconsuming process to do. Different WebView implementations on Android is troubling this issue. Best is to make sure it is working on a Nexus device with KitKat or newer, and then work-around issues on a Galaxy with KitKat or newer. When that is done, test the app on a Galaxy device with Jelly Bean. Other devices are less common and/or more stock then Galaxy. And don't forget iOS 7 and 8 and Windows Phone 7 and 8 when you are going to publish your app on those platforms too.
